Name:           cde-desktop
Version:        2.5.3^20260813git45420a3ec
Release:        1%{?dist}
Summary:        Common Desktop Environment

# CDE program/library code is LGPL-2.0-or-later. Its media and
# documentation include CC-BY-SA-3.0 material. The source tree also
# carries historical BSD-4-Clause, MIT/Expat, X11 and NTP material.
# The embedded ksh93u+m tree is EPL-2.0.
License:        LGPL-2.0-or-later AND CC-BY-SA-3.0 AND BSD-4-Clause AND MIT AND X11 AND NTP AND EPL-2.0
URL:            https://sourceforge.net/projects/cdesktopenv/

# Post-2.5.3 snapshot from signed Git commit:
# 45420a3ec0e318fed336b83ceda32a519ed861f2
#
# Generated deterministically with:
#
# git archive --format=tar \
#   --prefix=cde-desktop-2.5.3-20260813git45420a3ec/ \
#   45420a3ec0e318fed336b83ceda32a519ed861f2 |
#   gzip -n -9
#
# SHA-256:
# 42035105d55f5ecb91a1160568aedeefeab2ce03696337665e13720d245f6b79
Source0:        %{name}-%{version}.tar.gz

Patch0:         cde-motif-displayp-have-config-h.patch
Patch1:         cde-rpm-unprivileged-install-hooks.patch

# The bundled ksh93 build replaces CCFLAGS with its SHOPT definitions.
# Preserve RPM compiler hardening flags when building its bootstrap tools.
Patch2:         cde-rpm-dtksh-hardened-cflags.patch

# dthelp's eltdef objects consume headers generated by CDONE.  Express that
# ordering explicitly so parallel make cannot compile against a partial header.
Patch3:         cde-dthelp-eltdef-generated-header-order.patch

# Dt/Saver.h exposes X11 types but historically did not include their
# definitions, making the installed public header non-self-contained.
Patch4:         cde-saver-header-x11-types.patch

BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  bdftopcf
BuildRequires:  binutils
BuildRequires:  bison
BuildRequires:  cpp
BuildRequires:  flex
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  glibc-common
BuildRequires:  gzip
BuildRequires:  ksh
BuildRequires:  libICE-devel
BuildRequires:  libSM-devel
BuildRequires:  libX11-devel
BuildRequires:  libXau-devel
BuildRequires:  libXaw-devel
BuildRequires:  libXdmcp-devel
BuildRequires:  libXext-devel
BuildRequires:  libXinerama-devel
BuildRequires:  libXmu-devel
BuildRequires:  libXpm-devel
BuildRequires:  libXrender-devel
BuildRequires:  libXScrnSaver-devel
BuildRequires:  libXt-devel
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  libtirpc-devel
BuildRequires:  libtool
BuildRequires:  libutempter-devel
BuildRequires:  libxcrypt-devel
BuildRequires:  lmdb-devel
BuildRequires:  m4
BuildRequires:  make
BuildRequires:  mkfontscale
BuildRequires:  motif-devel
BuildRequires:  ncompress
BuildRequires:  opensp
BuildRequires:  pam-devel
BuildRequires:  perl-interpreter
BuildRequires:  pkgconf-pkg-config
BuildRequires:  rpcgen
BuildRequires:  sessreg
BuildRequires:  tcl-devel
BuildRequires:  xorg-x11-server-utils
BuildRequires:  libXp-devel
BuildRequires:  xorg-x11-proto-devel

Requires:       cpp
Requires:       sessreg
Requires:       xorg-x11-server-utils

%description
The Common Desktop Environment (CDE) is a desktop environment for Unix
and Unix-like systems. This package provides a monolithic CDE desktop
using the native Enterprise Linux filesystem layout.

%package devel
Summary:        Development files for the Common Desktop Environment
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       libtirpc-devel%{?_isa}
Requires:       libXinerama-devel%{?_isa}
Requires:       libXp-devel%{?_isa}
Requires:       libXt-devel%{?_isa}
Requires:       motif-devel%{?_isa}
Requires:       xorg-x11-proto-devel

%description devel
Header files, linker interfaces, and API manual pages for developing
software against the Common Desktop Environment libraries.

%prep
# RPM uses caret syntax for this post-release snapshot version, but CDE's
# historical DocBook instant transformation language treats '^' as syntax.
# Keep the caret in RPM metadata while using a caret-free source directory.
%autosetup -n cde-desktop-2.5.3-20260813git45420a3ec -p1

%build
cd cde

./autogen.sh

%configure \
    --sharedstatedir=%{_localstatedir} \
    --docdir=%{_defaultdocdir}/cde \
    --with-cde-data-dir=%{_datadir}/cde \
    --with-cde-config-dir=%{_sysconfdir}/cde \
    --with-cde-state-dir=%{_localstatedir}/lib/cde \
    --with-cde-libexec-dir=%{_libexecdir}/cde \
    --with-pam-dir=%{_sysconfdir}/pam.d

%make_build

%install
cd cde

%make_install

# Fedora/EPEL packages should not ship libtool archives.  CDE also installs
# shared implementations of these libraries, so omit their static copies.
rm -f %{buildroot}%{_libdir}/*.la
rm -f %{buildroot}%{_libdir}/*.a

# Upstream currently does not create the CDE state hierarchy.
install -d -m 0755 \
    %{buildroot}%{_localstatedir}/lib/cde

install -d -m 0755 \
    %{buildroot}%{_localstatedir}/lib/cde/appconfig

install -d -m 0755 \
    %{buildroot}%{_localstatedir}/lib/cde/appconfig/appmanager

# Preserve the upstream dtcm calendar spool policy.
test -d %{buildroot}%{_localstatedir}/spool/calendar

test "$(
    stat -c '%a' %{buildroot}%{_localstatedir}/spool/calendar
)" = "755"

# The downstream RPM patch must leave these binaries non-privileged
# during the unprivileged staged install.
for program in dtappgather dtmail dtterm dtsession; do
    path="%{buildroot}%{_bindir}/${program}"

    test -f "$path"

    mode="$(stat -c '%a' "$path")"

    test "$mode" = "755" || {
        echo "ERROR: unexpected staged mode for ${program}: ${mode}" >&2
        exit 1
    }
done

# Run the generic FHS validator against the actual RPM buildroot.
./util/check-fhs.sh %{buildroot}

%check
# More RPM-level checks will be added after the installed-file inventory
# has been derived and the package can proceed through binary assembly.


%files
%license %{_docdir}/cde/COPYING
%doc %{_docdir}/cde/CONTRIBUTORS
%doc %{_docdir}/cde/HISTORY
%doc %{_docdir}/cde/README.md
%doc %{_docdir}/cde/copyright

# System configuration.
%dir %{_sysconfdir}/cde
%dir %{_sysconfdir}/cde/fontaliases
%config(noreplace) %{_sysconfdir}/cde/fontaliases/fonts.alias
%config(noreplace) %{_sysconfdir}/pam.d/dtlogin
%config(noreplace) %{_sysconfdir}/pam.d/dtsession

# Runtime commands.
%{_bindir}/Xsession
%{_bindir}/dsdm
%{_bindir}/dtaction
%{_bindir}/dtappintegrate
%{_bindir}/dtbuilder
%{_bindir}/dtcalc
%{_bindir}/dtchooser
%{_bindir}/dtcm
%{_bindir}/dtcm_delete
%{_bindir}/dtcm_editor
%{_bindir}/dtcm_insert
%{_bindir}/dtcm_lookup
%{_bindir}/dtcodegen
%{_bindir}/dtcreate
%{_bindir}/dtdbcache
%{_bindir}/dtdocbook2infolib
%{_bindir}/dtdocbook2man
%{_bindir}/dtdocbook2sdl
%{_bindir}/dtdspmsg
%{_bindir}/dterror.ds
%{_bindir}/dtexec
%{_bindir}/dtfile
%{_bindir}/dtfile_copy
%{_bindir}/dtfile_error
%{_bindir}/dtfplist
%{_bindir}/dtgreet
%{_bindir}/dthello
%{_bindir}/dthelp_ctag1
%{_bindir}/dthelp_htag1
%{_bindir}/dthelp_htag2
%{_bindir}/dthelpgen
%{_bindir}/dthelpgen.dtsh
%{_bindir}/dthelpprint
%{_bindir}/dthelpprint.sh
%{_bindir}/dthelptag
%{_bindir}/dthelpview
%{_bindir}/dticon
%{_bindir}/dtimsstart
%{_bindir}/dtinfo
%{_bindir}/dtksh
%{_bindir}/dtlogin
%{_bindir}/dtlp
%{_bindir}/dtlpsetup
%{_bindir}/dtmailpr
%{_bindir}/dtopen
%{_bindir}/dtopen_image
%{_bindir}/dtopen_pdf
%{_bindir}/dtopen_ps
%{_bindir}/dtopen_video
%{_bindir}/dtpad
%{_bindir}/dtpdm
%{_bindir}/dtpdmd
%{_bindir}/dtprintegrate
%{_bindir}/dtprintinfo
%{_bindir}/dtscreen
%{_bindir}/dtsearchpath
%{_bindir}/dtsession_res
%{_bindir}/dtspcd
%{_bindir}/dtsrclean
%{_bindir}/dtsrcreate
%{_bindir}/dtsrdbrec
%{_bindir}/dtsrdelete
%{_bindir}/dtsrhan
%{_bindir}/dtsrindex
%{_bindir}/dtsrkdump
%{_bindir}/dtsrload
%{_bindir}/dtstyle
%{_bindir}/dttypes
%{_bindir}/dtwm
%{_bindir}/huffcode
%{_bindir}/rpc.cmsd
%{_bindir}/rpc.ttdbserver
%{_bindir}/tt_type_comp
%{_bindir}/ttauth
%{_bindir}/ttcp
%{_bindir}/ttdbck
%{_bindir}/ttmv
%{_bindir}/ttrm
%{_bindir}/ttrmdir
%{_bindir}/ttsession
%{_bindir}/ttsnoop
%{_bindir}/tttar
%{_bindir}/tttrace

# Runtime privilege metadata is assigned by RPM, not by make install.
%attr(4755,root,root) %{_bindir}/dtappgather
%attr(2755,root,mail) %{_bindir}/dtmail
%attr(0755,root,root) %{_bindir}/dtterm
%attr(0755,root,root) %{_bindir}/dtsession

# Versioned runtime libraries.
%{_libdir}/libDtHelp.so.2
%{_libdir}/libDtHelp.so.2.1.0
%{_libdir}/libDtMmdb.so.2
%{_libdir}/libDtMmdb.so.2.0.1
%{_libdir}/libDtMrm.so.2
%{_libdir}/libDtMrm.so.2.1.0
%{_libdir}/libDtPrint.so.2
%{_libdir}/libDtPrint.so.2.1.0
%{_libdir}/libDtSearch.so.2
%{_libdir}/libDtSearch.so.2.1.0
%{_libdir}/libDtSvc.so.2
%{_libdir}/libDtSvc.so.2.1.0
%{_libdir}/libDtTerm.so.2
%{_libdir}/libDtTerm.so.2.1.0
%{_libdir}/libDtWidget.so.2
%{_libdir}/libDtWidget.so.2.1.0
%{_libdir}/libDtXinerama.so.2
%{_libdir}/libDtXinerama.so.2.1.0
%{_libdir}/libcsa.so.2
%{_libdir}/libcsa.so.2.1.0
%{_libdir}/libtt.so.2
%{_libdir}/libtt.so.2.1.0

# Private runtime libraries and helpers.
%{_libdir}/cde
%{_libdir}/dtksh
%{_libexecdir}/cde

# Architecture-independent CDE runtime data.
%{_datadir}/cde

# Runtime/state directories.
%dir %attr(0755,root,root) %{_localstatedir}/lib/cde
%dir %attr(0755,root,root) %{_localstatedir}/lib/cde/appconfig
%dir %attr(0755,root,root) %{_localstatedir}/lib/cde/appconfig/appmanager
%dir %attr(0755,root,root) %{_localstatedir}/spool/calendar

# User commands.
%{_mandir}/man1/dsdm.1*
%{_mandir}/man1/dt*.1*
%{_mandir}/man1/huffcode.1*
%{_mandir}/man1/ksh-cde.1*
%{_mandir}/man1/tt*.1*

# Administrative commands.
%{_mandir}/man1m/dtspcd.1m*
%{_mandir}/man1m/rpc.cmsd.1m*
%{_mandir}/man1m/tt*.1m*

# CDE and ToolTalk formats/protocols.
%{_mandir}/man4/BIL.4*
%{_mandir}/man4/Deposit.4*
%{_mandir}/man4/Display.4*
%{_mandir}/man4/Dt*.4*
%{_mandir}/man4/Edit.4*
%{_mandir}/man4/Get_*.4*
%{_mandir}/man4/Instantiate.4*
%{_mandir}/man4/Lower.4*
%{_mandir}/man4/Mail.4*
%{_mandir}/man4/Modified.4*
%{_mandir}/man4/Pause.4*
%{_mandir}/man4/Print.4*
%{_mandir}/man4/Quit.4*
%{_mandir}/man4/Raise.4*
%{_mandir}/man4/Resume.4*
%{_mandir}/man4/Revert*.4*
%{_mandir}/man4/Save*.4*
%{_mandir}/man4/Set_*.4*
%{_mandir}/man4/Signal.4*
%{_mandir}/man4/Started.4*
%{_mandir}/man4/Status.4*
%{_mandir}/man4/Stopped.4*
%{_mandir}/man4/Translate.4*
%{_mandir}/man4/dt*.4*
%{_mandir}/man4/mt-libtt-intro.4*
%{_mandir}/man4/startlog.4*
%{_mandir}/man4/tttracefile.4*

# Runtime API/resource reference pages.
%{_mandir}/man5/Dt*.5*
%{_mandir}/man5/Tt*.5*
%{_mandir}/man5/csa*.5*
%{_mandir}/man5/dt*.5*
%{_mandir}/man6/ttsnoop.6*

%files devel
%dir %{_includedir}/Dt
%{_includedir}/Dt/*
%dir %{_includedir}/Tt
%{_includedir}/Tt/*
%dir %{_includedir}/csa
%{_includedir}/csa/*

# Linker interfaces for the versioned shared libraries.
%{_libdir}/libDtHelp.so
%{_libdir}/libDtMmdb.so
%{_libdir}/libDtMrm.so
%{_libdir}/libDtPrint.so
%{_libdir}/libDtSearch.so
%{_libdir}/libDtSvc.so
%{_libdir}/libDtTerm.so
%{_libdir}/libDtWidget.so
%{_libdir}/libDtXinerama.so
%{_libdir}/libcsa.so
%{_libdir}/libtt.so

# CDE, CSA, and ToolTalk programming interfaces.
%{_mandir}/man3/Dt*.3*
%{_mandir}/man3/csa_*.3*
%{_mandir}/man3/tt*.3*

%changelog
* Thu Aug 13 2026 Reaper <JohnGrimmReaper@disroot.org> - 2.5.3^20260813git45420a3ec-1
- Initial EPEL 9 packaging for post-2.5.3 CDE snapshot
