MAINTAINERCLEANFILES = Makefile.in

SUBDIRS = libDtMail MotifApp dtmail dtmailpr

noinst_HEADERS = \
    include/DtMail/Buffer.hh \
    include/DtMail/DtLanguages.hh \
    include/DtMail/DtMail.h \
    include/DtMail/DtMail.hh \
    include/DtMail/DtMailError.hh \
    include/DtMail/DtMailServer.hh \
    include/DtMail/DtMailTypes.h \
    include/DtMail/DtMailValues.hh \
    include/DtMail/DtVirtArray.hh \
    include/DtMail/FileShare.hh \
    include/DtMail/HashTable.hh \
    include/DtMail/IO.hh \
    include/DtMail/ObjectKey.hh \
    include/DtMail/options_util.h \
    include/MotifApp/AskFirstCmd.h \
    include/MotifApp/BasicComponent.h \
    include/MotifApp/BusyPixmap.h \
    include/MotifApp/ButtonInterface.h \
    include/MotifApp/Cmd.h \
    include/MotifApp/CmdInterface.h \
    include/MotifApp/CmdList.h \
    include/MotifApp/DialogManager.h \
    include/MotifApp/Help.hh \
    include/MotifApp/IconifyCmd.h \
    include/MotifApp/InfoDialogManager.h \
    include/MotifApp/InterruptibleCmd.h \
    include/MotifApp/ManageCmd.h \
    include/MotifApp/MenuWindow.h \
    include/MotifApp/MotifCmds.h \
    include/MotifApp/NoUndoCmd.h \
    include/MotifApp/PixmapCycler.h \
    include/MotifApp/PromptDialogManager.h \
    include/MotifApp/QuestionDialogManager.h \
    include/MotifApp/QuitCmd.h \
    include/MotifApp/ScrollingList.h \
    include/MotifApp/SelectFileCmd.h \
    include/MotifApp/UIComponent.h \
    include/MotifApp/UndoCmd.h \
    include/MotifApp/WarnNoUndoCmd.h \
    include/MotifApp/WorkingDialogManager.h \
    include/utils/EUSDebug.hh \
    include/utils/str_utils.h
