MAINTAINERCLEANFILES = Makefile.in

SUBDIRS = libAButil libABobj libABobjXm libABil abmf ab

noinst_HEADERS = \
    include/ab/util_types.h \
    include/ab_private/AB.h \
    include/ab_private/UilDef.h \
    include/ab_private/XmAll.h \
    include/ab_private/abio.h \
    include/ab_private/istr.h \
    include/ab_private/obj.h \
    include/ab_private/obj_list.h \
    include/ab_private/objxm.h \
    include/ab_private/trav.h \
    include/ab_private/util.h \
    include/ab_private/util_ds.h \
    include/ab_private/util_err.h
